// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbpI7l__Dg5u5Pp-2-zPADuSNex_rIAKk',
    appId: '1:624360880066:web:c7e8de270c55ff9c4f085b',
    messagingSenderId: '624360880066',
    projectId: 'reefs-nav',
    authDomain: 'reefs-nav.firebaseapp.com',
    storageBucket: 'reefs-nav.appspot.com',
    measurementId: 'G-KKYCJ06VBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDqVJuhcgTV35o7OTxLDKcl9fHETJCck',
    appId: '1:624360880066:android:15a0656bfc93fe414f085b',
    messagingSenderId: '624360880066',
    projectId: 'reefs-nav',
    storageBucket: 'reefs-nav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmbF3f_7J_Vke0mrrslc1vHlyG3j6fPc',
    appId: '1:624360880066:ios:373ae641315f56e04f085b',
    messagingSenderId: '624360880066',
    projectId: 'reefs-nav',
    storageBucket: 'reefs-nav.appspot.com',
    iosBundleId: 'com.example.reefsNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdmbF3f_7J_Vke0mrrslc1vHlyG3j6fPc',
    appId: '1:624360880066:ios:84e01471cdc5eccd4f085b',
    messagingSenderId: '624360880066',
    projectId: 'reefs-nav',
    storageBucket: 'reefs-nav.appspot.com',
    iosBundleId: 'com.example.reefsNav.RunnerTests',
  );
}
